function(__cspec_assert_be_target positive actual)
    if(positive AND NOT TARGET "${actual}")
        expect_fail("Expected target '${actual}' to exist")
    elseif(NOT positive AND TARGET "${actual}")
        expect_fail("Expected target '${actual}' not to exist")
    endif()
endfunction()
